
KERDIR	= kernel/

KEROBJ 		=
KEROBJ		+= kernel.o
KEROBJ		+= main.o
KEROBJ		+= clock.o
KEROBJ		+= i8259.o
KEROBJ 		+= global.o
KEROBJ		+= protect.o
#KEROBJ		+= sched.o
#KEROBJ		+= init_task.o

OBJS    += $(addprefix $(KERDIR), $(KEROBJ))
